# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: alyson.pain@ecole-hexagone.com
author_name: alyspn
contract_name: contrat_un
deployment_language: python
preset_name: production
project_name: CorentinAlyson-contracts

